version: "3.8"

services:
  reconai:
    build:
      context: .
      dockerfile: docker/main.Dockerfile
    volumes:
      - ./app:/app
      - ./outputs:/outputs
    environment:
      - SHODAN_API_KEY=${SHODAN_KEY}
    # Remove any command or entrypoint overrides
    entrypoint: ["python", "main.py"]
    depends_on:
      - sublister_builder
      - nmap_builder
      - whatweb_builder

  sublister_builder:
    build:
      context: .
      dockerfile: docker/sublister.Dockerfile
    volumes:
      - ./outputs:/sublister/output
    image: recon-sublister
    profiles: ["build-only"]

  nmap_builder:
    image: instrumentisto/nmap
    volumes:
      - ./outputs:/scans
    profiles: ["build-only"]

  whatweb_builder:
    build:
      context: .
      dockerfile: docker/whatweb.Dockerfile
    volumes:
      - ./outputs:/whatweb/output
    image: recon-whatweb
    profiles: ["build-only"]
